# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Publish NPM on Release Created

on:
  push:
    branches: [ "master" ]

jobs:
  compare-versions:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.fetch-new-version.outputs.version }}
      updated: ${{ steps.fetch-new-version.outputs.version != steps.fetch-released-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the new version from package.json
        id: fetch-new-version
        run: |
          version=$(jq -r '.version' package.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Fetch latest NPM package version
        id: fetch-released-version
        run: |
          http_content=$(curl -s https://registry.npmjs.org/shikimori-graphql-api-lightweight-client/latest)
          version=$(echo $http_content | jq -r '.version')
          echo "version=$version" >> "$GITHUB_OUTPUT"

  publish-npm:
    runs-on: ubuntu-latest
    needs: compare-versions
    if: ${{ needs.compare-versions.outputs.updated == 'true' }}
    steps:
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs: [ compare-versions, publish-npm ]
    if: ${{ needs.compare-versions.outputs.updated == 'true' }}
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ needs.compare-versions.outputs.version }}
          tag_name: v${{ needs.compare-versions.outputs.version }}
